--total customers by countries
SELECT 'Total Customers By Country' as Metrics,
c.Country as Dimension_Value , 
count(c.customer_key) AS Measure_Value
from gold.dim_customers c 
group by Country
order by count(c.customer_key) desc

---total customers by gender
SELECT 'Total Customers by Gender' as Metrics, 
Gender as Dimension_Value , 
count(customer_key) AS Measure_Value
from gold.dim_customers 
group by Gender
order by count(customer_key) DESC

--total products by category
select 'Total Products by Category' as Metrics, 
Category as Dimension_Value , 
count(Product_key) AS Measure_Value 
from gold.dim_products 
group by Category

--average costs in each category
select 'Average Cost by Category' as Metrics, 
Category as Dimension_Value , AVG(COST) AS Measure_Value 
from gold.dim_products 
group by Category
order by AVG(COST) DESC;

--total revenue generated for each category
select 'Total Revenue' as Metrics, 
P.Category as Dimension_Value , 
sum(f.Sales) AS Measure_Value 
from gold.fact_sales f
left join 
gold.dim_products p
on f.Product_key = p.Product_key
group by p.Category
ORDER BY sum(f.Sales) desc;

---total revenue is generated by each customer
select 'Total Revenue By Customer' as Metrics, 
c.Customer_ID as Dimension_Value , 
sum(f.Sales) AS Measure_Value 
from gold.fact_sales f
left join 
gold.dim_customers c
on f.customer_key = c.customer_key
group by c.Customer_ID
order by sum(f.Sales) desc

--Distribution of sold items across countries--
select 'Total distribution of Sold items by countries' as Metrics, 
c.Country as Dimension_Value , 
sum(f.Qunatity) AS Measure_Value 
from gold.fact_sales f
left join 
gold.dim_customers c
on f.customer_key = c.customer_key
group by c.Country
ORDER BY sum(f.Qunatity)

---Top 5 Highest Revenue Generating Products-----
SELECT top 5
sum(f.Sales) AS TOTAL_SALES,
p.Product_Name
FROM gold.fact_sales f
LEFT JOIN
gold.dim_products p
on f.Product_key = p.Product_key
GROUP BY p.Product_Name
order by sum(f.Sales) desc

--Top 5 least Revenue Generating Products-----
SELECT top 5
sum(f.Sales) AS TOTAL_SALES,
p.Product_Name
FROM gold.fact_sales f
LEFT JOIN
gold.dim_products p
on f.Product_key = p.Product_key
GROUP BY p.Product_Name
order by sum(f.Sales) asc




---------------------------------
select * from gold.dim_customers
select * from gold.dim_products
select * from gold.fact_sales
---------------------------------

